library(diffr)
library(here)
diffr(
  here(
    "ref_scripts/comparing_files",
    "2024-12-06_water_quality_map_dataset_arcgis_copy.csv"
  ),
  here(
    "ref_scripts/comparing_files",
    "2024-12-06_water_quality_map_dataset_local_copy.csv"
  )
)
